// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _GetBatteryProductsEp } from '../src/api/getBatteryProducts';
import type { default as _SubmitLeadEp } from '../src/api/submitLead';

type _GetBatteryProductsCfg = typeof _GetBatteryProductsEp;
export type GetBatteryProductsInputType = NonNullable<_GetBatteryProductsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBatteryProductsCfg['execute']>[0]['input'];
export type GetBatteryProductsOutputType = Awaited<ReturnType<_GetBatteryProductsCfg['execute']>>;
export const getBatteryProducts = createCaller<GetBatteryProductsInputType, GetBatteryProductsOutputType>('getBatteryProducts');

type _SubmitLeadCfg = typeof _SubmitLeadEp;
export type SubmitLeadInputType = NonNullable<_SubmitLeadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitLeadCfg['execute']>[0]['input'];
export type SubmitLeadOutputType = Awaited<ReturnType<_SubmitLeadCfg['execute']>>;
export const submitLead = createCaller<SubmitLeadInputType, SubmitLeadOutputType>('submitLead');


export const api = {
  getBatteryProducts,
  submitLead,
};
