// Generated by Zite. Do not edit.
declare namespace NodeJS {
  interface ProcessEnv {
    /** Public URL of the current app. */
    ZITE_APP_URL: string;
    /** API key for your Battery Database's product-listing connection */
    ZITE_BATTERY_DB_API_KEY: string;
    /** Full address of your Battery Database's product-listing connection (e.g. https://2am5kavyuw.zite.so/api/listProducts) */
    ZITE_BATTERY_DB_URL: string;
    /** API key for your external CRM's lead intake (kwpcsjjq6u.zite.so) */
    ZITE_CRM_API_KEY: string;
    [key: string]: string | undefined;
  }
}
